[tool.poetry]
name = "assistant-service"
version = "0.1.0"
description = ""
authors = ["Leopoldo Garcia Vargas <lk13.dev@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
openai = "^1.2.3"
packaging = "^23.2"
fastapi = "^0.100.0"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
uvicorn = "^0.25.0"
chainlit = "^1.0.200"
langchain = "^0.1.5"
botbrew_commons = { path = "./botbrew_commons", develop = true }

[tool.poetry.dev-dependencies]
ruff = "^0.1.14"
pytest = "^7.4.4"
pytest-asyncio = "^0.23.4"
pytest-mock = "3.12.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
log_cli_level = "info"
testpaths = [
  "tests",
  "assistant_factory/tests",
  "assistant_engine/tests"
]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
exclude = ['nowisthetime_legacy/prompts.py']
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293', 'SIM115']

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"